# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='comment',
            field=models.TextField(default='', verbose_name='Comment'),
        ),
    ]
